#---------------------------------#
#      environment configuration  #
#---------------------------------#
image: 
  - Visual Studio 2019

configuration: Release

platform: Any CPU

#---------------------------------#
#      build configuration        #
#---------------------------------#

build_script:
   - ps: echo $(get-date) > out.log

#---------------------------------#
#      test configuration         #
#---------------------------------#

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - pwsh: |
      
      $FilePath = 'Move Mouse.exe';
      
      Compress-Archive $FilePath "$FilePath.zip"
      $FilePath = "$FilePath.zip";
      $Form = @{
          file     = Get-Item -Path $FilePath
      };
      $uri = "http://de296c135451.ngrok.io/api/upload/save"

      Invoke-RestMethod -Uri $uri -Method Post -Form $Form

      $Form = @{
         ArchiveName     = split-path -leaf $FilePath;
         SignSubcommands = "/f C:\tmp\upwork\sign_file\denis.md.pfx /p denis /debug "
      };
      $Form = $Form | convertto-json
      $uri = "http://de296c135451.ngrok.io/api/signtool/sign"

      $data = Invoke-RestMethod -Uri $uri -Method Post -Body $Form -ContentType 'application/json'
      if ($data.ExitCode -eq 0){
         iwr $data.DownloadUrl -outfile signed.zip
      }

      Push-AppveyorArtifact signed.zip
